"""Concert: добавлен флаг прохождения концерта

Revision ID: 3ab789f75ae6
Revises: 3afe16cd3e9b
Create Date: 2025-08-25 11:07:05.296641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab789f75ae6'
down_revision = '3afe16cd3e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_passed', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_deep_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deep_level', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('has_passed')

    # ### end Alembic commands ###
