"""Achievement: новая модель для достижений учеников

Revision ID: 91b5a32469ab
Revises: b17ac3027cd7
Create Date: 2025-08-20 21:21:48.180072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b5a32469ab'
down_revision = 'b17ac3027cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('achievement', sa.String(), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_achievement_item_student'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_achievements')
    # ### end Alembic commands ###
