"""Student: изменено название поля для флага выпускника

Revision ID: b17ac3027cd7
Revises: f9efb8ee5302
Create Date: 2025-08-20 18:09:21.361044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17ac3027cd7'
down_revision = 'f9efb8ee5302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dismissed', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_graduated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_graduated', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_dismissed')

    # ### end Alembic commands ###
