"""Student: добавлен флаг углубленного изучения

Revision ID: c9c840bc571e
Revises: 91b5a32469ab
Create Date: 2025-08-20 21:34:25.720049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c840bc571e'
down_revision = '91b5a32469ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deep_level', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_deep_level')

    # ### end Alembic commands ###
