"""DepartmentReportItem: добавлена модель отчёта по успеваемости по отделениям

Revision ID: ed3847421fa8
Revises: 3ab789f75ae6
Create Date: 2025-08-28 16:34:56.119116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3847421fa8'
down_revision = '3ab789f75ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('got_best', sa.Integer(), nullable=True),
    sa.Column('got_good', sa.Integer(), nullable=True),
    sa.Column('got_avg', sa.Integer(), nullable=True),
    sa.Column('got_bad', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_department_report_items_department'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'academic_year', 'term', name='uq_department_report_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_report_items')
    # ### end Alembic commands ###
