"""Student: добавлены поля для выпускников и отчисленных

Revision ID: f9efb8ee5302
Revises: c24c6df5ba24
Create Date: 2025-08-20 17:34:59.274758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9efb8ee5302'
down_revision = 'c24c6df5ba24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_graduated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dismission_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dismission_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cert_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('cert_no')
        batch_op.drop_column('dismission_reason')
        batch_op.drop_column('dismission_date')
        batch_op.drop_column('is_graduated')

    # ### end Alembic commands ###
